name: Scrape Football API

on:
  workflow_dispatch:
    
  repository_dispatch:
    types:
      - webhook
  
  schedule:
    - cron: '0 */2 * * *'

jobs:
  execute-deno-function:
    runs-on: ubuntu-22.04
    env:
      API_FOOTBALL_BASE_URL: ${{ secrets.API_FOOTBALL_BASE_URL }}
      API_FOOTBALL_API_KEY: ${{ secrets.API_FOOTBALL_API_KEY }}
      API_FOOTBALL_API_HOST: ${{ secrets.API_FOOTBALL_API_HOST }}
    steps:
      - name: Configure Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: '1.37.2'
      - name: Execute Scrapper
        run: |
          deno run --allow-net --allow-write --allow-env --env API_FOOTBALL_BASE_URL=$API_FOOTBALL_BASE_URL API_FOOTBALL_API_KEY=$API_FOOTBALL_API_KEY API_FOOTBALL_API_HOST=$API_FOOTBALL_API_HOST src/cron/scrape.ts
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update Api Football data"
          git push origin main
